// backend/utils/data.js
const items = [
    {
      id: 1,
      image: "./images/dosa.jpg",
      name: "Dosa",
      category: "breakfast",
      price: "40Rs",
      description: "ssss lorem mmm,sdddd ddd ss aaa ss",
      quantity:1,
    },
    {
      id: 2,
      image: "./images/curd-ricee.jpg",
      name: "curd rice",
      category: "lunch",
      price: "80rs",
      description: "ssss lorem mmm,sdddd ddd ss aaa ss",
      quantity:1,
    },
    {
      id: 3,
      image: "./images/gobhi.jpg",
      name: "Gobhi",
      category: "evening",
      price: "50rs",
      description: "ssss lorem mmm,sdddd ddd ss aaa ss",
      quantity:1,
    },
    {
      id: 4,
      image: "./images/idli.jpg",
      name: "Idli",
      category: "breakfast",
      price: "40rs",
      description: "ssss lorem mmm,sdddd ddd ss aaa ss",
      quantity:1,
    },
    {
      id: 5,
      image: "./images/meals.jpg",
      name: "indian Thali",
      category: "lunch",
      price: "140rs",
      description: "ssss lorem mmm,sdddd ddd ss aaa ss",
      quantity:1,
    },
    {
      id: 6,
      image: "./images/momos.jpg",
      name: "momos",
      category: "evening",
      price: "45rs",
      description: "ssss lorem mmm,sdddd ddd ss aaa ss",
      quantity:1,
    },
    {
      id: 7,
      image: "./images/puri.jpg",
      name: "puri",
      category: "breakfast",
      price: "40rs",
      description: "ssss lorem mmm,sdddd ddd ss aaa ss",
      quantity:1,
    },
    {
      id: 8,
      image: "./images/thali.jpg",
      name: "thali",
      category: "lunch",
      price: "150rs",
      description: "ssss lorem mmm,sdddd ddd ss aaa ss",
      quantity:1,
    },
    {
      id: 9,
      image: "./images/pakoda.jpg",
      name: "pakoda",
      category: "evening",
      price: "30rs",
      description: "ssss lorem mmm,sdddd ddd ss aaa ss",
      quantity:1,
    },
    {
      id: 10,
      image: "./images/veg-biriyani2.jpg",
      name: "biriyani",
      category: "lunch",
      price: "140rs",
      description: "ssss lorem mmm,sdddd ddd ss aaa ss",
      quantity:1,
    },
  ];
//   export default items;
module.exports = items;
  