const Menu = [
  {
    id: 1,
    image: "./images/dosa.jpg",
    name: "Dosa",
    category: "breakfast",
    price: 40,
    description: "ssss lorem mmm,sdddd ddd ss aaa ss",
    quantity:1,
  },
  {
    id: 2,
    image: "./images/curd-ricee.jpg",
    name: "curd rice",
    category: "lunch",
    price: 80,
    description: "ssss lorem mmm,sdddd ddd ss aaa ss",
    quantity:1,
  },
  {
    id: 3,
    image: "./images/gobhi.jpg",
    name: "Gobhi",
    category: "evening",
    price: 50,
    description: "ssss lorem mmm,sdddd ddd ss aaa ss",
    quantity:1,
  },
  {
    id: 4,
    image: "./images/idli.jpg",
    name: "Idli",
    category: "breakfast",
    price: 40,
    description: "ssss lorem mmm,sdddd ddd ss aaa ss",
    quantity:1,
  },
  {
    id: 5,
    image: "./images/meals.jpg",
    name: "indian Thali",
    category: "lunch",
    price: 140,
    description: "ssss lorem mmm,sdddd ddd ss aaa ss",
    quantity:1,
  },
  {
    id: 6,
    image: "./images/momos.jpg",
    name: "momos",
    category: "evening",
    price: 45,
    description: "ssss lorem mmm,sdddd ddd ss aaa ss",
    quantity:1,
  },
  {
    id: 7,
    image: "./images/puri.jpg",
    name: "puri",
    category: "breakfast",
    price: 40,
    description: "ssss lorem mmm,sdddd ddd ss aaa ss",
    quantity:1,
  },
  {
    id: 8,
    image: "./images/thali.jpg",
    name: "thali",
    category: "lunch",
    price: 150,
    description: "ssss lorem mmm,sdddd ddd ss aaa ss",
    quantity:1,
  },
  {
    id: 9,
    image: "./images/pakoda.jpg",
    name: "pakoda",
    category: "evening",
    price: 30,
    description: "ssss lorem mmm,sdddd ddd ss aaa ss",
    quantity:1,
  },
  {
    id: 10, 
    image: "./images/veg-biriyani2.jpg",
    name: "biriyani",
    category: "lunch",
    price: 140,
    description: "ssss lorem mmm,sdddd ddd ss aaa ss",
    quantity:1,
  },
  {
    id:11,
    image:"./images/veg-biriyani",
    name:"Zaatari Chicken Seekh Shawarma",
    category:"lunch",
    price:199,
    description:"Chicken minced with onions and herbs \u0026 zatar barbecue on skewers and wrapped in a pita bread with tahini, garlic sauce and hummus Served",
    quantity:1,
},
{
  id:12,
  image:"https://apipics.s3.amazonaws.com/mexican_api/1.jpg",
  name:"Pressure cooker refried beans",
  category:"breakfast",
  price:200,
  description:"Chicken minced with onions and herbs \u0026 zatar barbecue on skewers and wrapped in a pita bread with tahini, garlic sauce and hummus Served",
  quantity:1,
},
{
  id:13,
  image:"https://apipics.s3.amazonaws.com/mexican_api/3.jpg",
  name:"Fishcake tacos",
  category:"breakfast",
  price:105,
  description:"bhdchrbch nui dedn  wedn sj ",
  quantity:1,
},
{
  id: 14,
  image: "./images/pakoda.jpg",
  name: "Tea",
  category: "Drinks",
  price: 30,
  description: "ssss lorem mmm,sdddd ddd ss aaa ss",
  quantity:1,
},
{
  id: 15,
  image: "./images/pakoda.jpg",
  name: "Coffee",
  category: "Drinks",
  price: 30,
  description: "ssss lorem mmm,sdddd ddd ss aaa ss",
  quantity:1,
},
];
export default Menu;

